[versions]
fabric_loader = "0.18.2"
fabric_api = "0.92.6+1.20.1"
forge = "1.20.1-47.4.10"
yarn = "1.20.1+build.1:v2"


[libraries]
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

[bundles]

fabric = ["fabric_loader", "fabric_api"]

[plugins]
architectury-plugin = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
loom = { id = "dev.architectury.loom", version = "1.11-SNAPSHOT" }
shadow = { id = "com.gradleup.shadow", version = "8.3.6" }
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version = "0.8.0" }